- name: Install Tools
  hosts: all

  tasks:
  - name: Install required packages
    ansible.builtin.apt:
      name:
        - python3
        - python3-pip
        - git
        - net-tools
        - curl
