- name: Install Tools
  hosts: all

  tasks:
  - name: Install required packages
    ansible.builtin.apt:
      name:
        - git
        - net-tools
        - curl
      update_cache: yes

  - name: Install Pritunl
    ansible.builtin.apt:
      name: pritunl
      state: latest
      update_cache: yes
